<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>13.0</LangVersion>
		<OutputItemType>Analyzer</OutputItemType>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<!--<ImplicitUsings>enable</ImplicitUsings>-->
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" PrivateAssets="all" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" PrivateAssets="all" GeneratePathProperty="true" />
	</ItemGroup>

	<PropertyGroup>
		<GetTargetPathDependsOn>$(GetTargetPathDependsOn);IncludeAnalyzerDependencies</GetTargetPathDependsOn>
	</PropertyGroup>

	<Target Name="IncludeAnalyzerDependencies">
		<ItemGroup>
			<!-- Reference directly from the NuGet package location -->
			<TargetPathWithTargetPlatformMoniker Include="$(PkgNewtonsoft_Json)\lib\netstandard2.0\Newtonsoft.Json.dll" IncludeRuntimeDependency="false" />
		</ItemGroup>
		<Message Text="Including DatabaseDefinition from: $(PkgNewtonsoft_Json)\lib\netstandard2.0\Newtonsoft.Json.dll" Importance="high" />
	</Target>

	<ItemGroup>
		<None Include="AnalyzerReleases.Shipped.md" />
		<None Include="AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\EZAccess.SourceGenerator.Abstractions\EZAccess.SourceGenerator.Abstractions.csproj" />
	</ItemGroup>
</Project>
