using System;
using System.Text;

namespace EZAccess.SourceGenerator.Builders;

internal abstract class CodeBuilderBase
{
	protected StringBuilder builder = new();
	protected int indentLevel = 0;

	protected void Indent() => indentLevel++;
	protected void Unindent() => indentLevel = Math.Max(0, indentLevel - 1);

	protected void AppendLine(string line = "")
	{
		builder.AppendLine($"{new string('\t', indentLevel)}{line}");
	}

	protected void BreakLine()
	{
		builder.AppendLine();
	}

	protected void WriteDisclaimer()
	{
		AppendLine("/*");
			Indent();
			AppendLine("This file is auto-generated by a code generator.");
			AppendLine("This code generator is written by EZ Access");
			AppendLine("Do not make edits in this file.");
			Unindent();
		AppendLine("*/");
		BreakLine();
	}

	protected void WriteComment(string comment)
	{
		foreach (var line in comment.Split(["\r\n"], StringSplitOptions.None)) {
			AppendLine($"// {line}");
		}
	}

	protected void StartBlock(string line)
	{
		AppendLine(line);
		AppendLine("{");
		Indent();
	}

	protected void EndBlock()
	{
		Unindent();
		AppendLine("}");
	}

	public void StartSummary(string? summary = null)
	{
		AppendLine("/// <summary>");
		if (summary is null) return;
		foreach (var line in summary.Split(["\r\n"], StringSplitOptions.None)) {
			AppendLine($"/// {line}");
		}
	}

	public void WriteSummary(string summary)
	{
		foreach (var line in summary.Split(["\r\n"], StringSplitOptions.None)) {
			AppendLine($"/// {line}");
		}
	}

	public void EndSummary()
	{
		AppendLine("/// </summary>");
	}
}
